/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.activator.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import vary.pseudocodigo.dsl.activator.ui.internal.ActivatorActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ActivatorExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ActivatorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ActivatorActivator.getInstance().getInjector(ActivatorActivator.VARY_PSEUDOCODIGO_DSL_ACTIVATOR_ACTIVATOR);
	}
	
}
