/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.c.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VaryGrammarUiModule extends vary.pseudocodigo.dsl.c.ui.AbstractVaryGrammarUiModule {
	public VaryGrammarUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
