/*
* generated by Xtext
*/
package vary.pseudocodigo.dsl.cpp;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class VaryGrammarStandaloneSetup extends VaryGrammarStandaloneSetupGenerated{

	public static void doSetup() {
		new VaryGrammarStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

