/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.activator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ActivatorUiModule extends vary.pseudocodigo.dsl.activator.ui.AbstractActivatorUiModule {
	public ActivatorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
