/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.cpp.ui.contentassist

import vary.pseudocodigo.dsl.cpp.ui.contentassist.AbstractVaryGrammarProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VaryGrammarProposalProvider extends AbstractVaryGrammarProposalProvider {
}
