/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.cpp;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VaryGrammarRuntimeModule extends vary.pseudocodigo.dsl.cpp.AbstractVaryGrammarRuntimeModule {

}
