/*
* generated by Xtext
*/
package vary.pseudocodigo.dsl.cpp.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VaryGrammarAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("vary/pseudocodigo/dsl/cpp/parser/antlr/internal/InternalVaryGrammar.tokens");
	}
}
