/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.activator.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractActivatorValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(vary.pseudocodigo.dsl.activator.activator.ActivatorPackage.eINSTANCE);
		return result;
	}
}
