/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.activator.ui.contentassist

import vary.pseudocodigo.dsl.activator.ui.contentassist.AbstractActivatorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ActivatorProposalProvider extends AbstractActivatorProposalProvider {
}
