/*
 * generated by Xtext
 */
package vary.pseudocodigo.dsl.activator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ActivatorRuntimeModule extends vary.pseudocodigo.dsl.activator.AbstractActivatorRuntimeModule {

}
