/*
* generated by Xtext
*/
package vary.pseudocodigo.dsl.activator.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ActivatorAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("vary/pseudocodigo/dsl/activator/parser/antlr/internal/InternalActivator.tokens");
	}
}
